In [2]:
import boto3
import pprint
from botocore.exceptions import ClientError
import os
import pandas as pd

In [23]:
def read_csv_to_df(bucket_name, object_name,file_name):
    """Download a file from an S3 bucket in local path and read it as DataFrame

    :param bucket_name: Bucket from where to download
    :param object_name: S3 object name to download
    :param file_name: File to save to
    :return: DataFrame, otherwise return False
    """
    s3 = boto3.client('s3')
    try:
        s3.download_file(bucket_name,object_name,file_name)
        df = pd.read_csv(file_name)
    except ClientError as e:
        logging.error(e)
        return False
    return df

In [12]:
def download_file(BUCKET_NAME, OBJECT_NAME, FILE_NAME):
    """Download a file from an S3 bucket

    :param bucket_name: Bucket from where to download
    :param object_name: S3 object name to download
    :param file_name: File to save to
    :return: True if file was downloaded, else False
    """
    s3 = boto3.client('s3')
    try:
        s3.download_file(BUCKET_NAME, OBJECT_NAME, FILE_NAME)
    except ClientError as e:
        logging.error(e)
        return False
    return True

In [27]:
s3 = boto3.client('s3')
bucket_name = 'data-eng-223-final-project'
directory1='Academy/'
directory2='Talent/'
data_ls = []

try:
    response = s3.list_objects_v2(Bucket=bucket_name, Prefix=directory1)
    
    # Check if any objects exist in the bucket
    if 'Contents' in response:
        objects = response['Contents']
        
        # Iterate over the objects and print their keys
        for obj in objects:
            object_key = obj['Key']
            if object_key.startswith('Academy/Data'):
                print(object_key)
                data_ls.append(object_key)
            
    else:
        print('No objects found in the bucket.')
except Exception as e:
    print(f"Error listing objects: {e}")
print(data_ls)

Academy/Data_28_2019-02-18.csv
Academy/Data_29_2019-03-04.csv
Academy/Data_30_2019-04-08.csv
Academy/Data_31_2019-05-20.csv
Academy/Data_32_2019-07-22.csv
Academy/Data_33_2019-08-05.csv
Academy/Data_34_2019-08-19.csv
Academy/Data_35_2019-09-23.csv
Academy/Data_36_2019-10-28.csv
Academy/Data_37_2019-11-18.csv
Academy/Data_38_2019-12-16.csv
Academy/Data_39_2019-12-30.csv
['Academy/Data_28_2019-02-18.csv', 'Academy/Data_29_2019-03-04.csv', 'Academy/Data_30_2019-04-08.csv', 'Academy/Data_31_2019-05-20.csv', 'Academy/Data_32_2019-07-22.csv', 'Academy/Data_33_2019-08-05.csv', 'Academy/Data_34_2019-08-19.csv', 'Academy/Data_35_2019-09-23.csv', 'Academy/Data_36_2019-10-28.csv', 'Academy/Data_37_2019-11-18.csv', 'Academy/Data_38_2019-12-16.csv', 'Academy/Data_39_2019-12-30.csv']

In [42]:
import boto3
import pandas as pd

s3 = boto3.client('s3')
bucket_name = 'data-eng-223-final-project'
data_ls = []

try:
    response = s3.list_objects_v2(Bucket=bucket_name)
    
    # Check if any objects exist in the bucket
    if 'Contents' in response:
        objects = response['Contents']
        
        # Iterate over the objects and print their keys
        for obj in objects:
            object_key = obj['Key']
            if object_key.startswith('Academy/Data'):
                # print(object_key)
                data_ls.append(object_key)
    else:
        print('No objects found in the bucket.')
        
except Exception as e:
    print(f"Error listing objects: {e}")

rows = 0
for obj_name in data_ls:
    file_name = obj_name.split('/')[-1]  # Extract the file name from the object key
    print(file_name)
    try:
        response = s3.get_object(Bucket=bucket_name, Key=obj_name)
        df = pd.read_csv(response['Body'])
        print(df.columns)
        display(df)
        
        rows+=df.shape[0]
        # Use the DataFrame 'df' for further processing or analysis
    except Exception as e:
        print(f"Error reading file {file_name}: {e}")
print(rows)

Data_28_2019-02-18.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Pyotr De Zuani,Trixie Orange,1,3,4,2,2,2,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Vince Scott,Trixie Orange,1,1,4,3,3,4,3,4,...,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
2,Kellie Althorp,Trixie Orange,3,4,1,1,5,2,2,3,...,6.0,8.0,5.0,8.0,3.0,7.0,8.0,8.0,8.0,6.0
3,Aida Bothams,Trixie Orange,4,2,2,3,3,1,7,6,...,8.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
4,Nettie Civitillo,Trixie Orange,5,4,3,1,1,6,2,5,...,7.0,6.0,6.0,6.0,8.0,8.0,8.0,7.0,3.0,7.0
5,Bernadette Gerardi,Trixie Orange,6,1,3,2,2,3,2,5,...,8.0,7.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0
6,Teddy Ham,Trixie Orange,4,4,2,1,4,1,4,4,...,8.0,8.0,7.0,5.0,8.0,7.0,8.0,8.0,8.0,8.0
7,Ivory Linnemann,Trixie Orange,2,1,3,1,3,4,1,3,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0
8,Onida Tregear,Trixie Orange,6,3,1,5,2,2,5,2,...,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
9,Jacki Pinkstone,Trixie Orange,2,1,2,2,4,2,4,1,...,8.0,8.0,5.0,8.0,7.0,8.0,8.0,8.0,8.0,5.0
10,Kaleb Cappel,Trixie Orange,4,5,5,4,1,3,4,3,...,8.0,8.0,8.0,7.0,8.0,8.0,8.0,5.0,6.0,8.0

Data_29_2019-03-04.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Gussy Mathias,John Sandbox,6,3,2,4,5,6,6.0,2.0,...,8.0,5.0,8.0,4.0,8.0,8.0,8.0,8.0,6.0,8.0
1,Shawn Bowmer,John Sandbox,8,2,2,1,3,5,1.0,2.0,...,7.0,7.0,8.0,7.0,8.0,7.0,8.0,8.0,8.0,8.0
2,Arda Disbrow,John Sandbox,2,2,4,2,2,4,5.0,3.0,...,3.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
3,El Durante,John Sandbox,2,2,5,4,3,1,3.0,5.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
4,Dionysus Garter,John Sandbox,3,2,1,3,4,5,4.0,1.0,...,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
5,Connor Gegg,John Sandbox,1,1,1,2,3,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Barrie Schruurs,John Sandbox,1,5,2,1,2,2,3.0,1.0,...,8.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
7,Fletcher Ayllett,John Sandbox,1,3,2,4,2,2,3.0,3.0,...,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
8,Slade Cannavan,John Sandbox,5,4,2,6,3,4,5.0,3.0,...,8.0,4.0,6.0,8.0,8.0,8.0,2.0,8.0,8.0,8.0
9,Bert Spall,John Sandbox,3,3,6,3,7,1,3.0,1.0,...,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0

Data_30_2019-04-08.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Denyse Worley,Edward Reinhart,4,3,2,1,6,1,3,1,...,8,8,8,8,8,8,5,8,8,8
1,Jard Antonowicz,Edward Reinhart,1,5,5,3,2,3,2,3,...,7,7,6,8,5,8,8,8,8,8
2,Burtie Clubley,Edward Reinhart,7,1,5,1,3,4,2,4,...,8,8,6,5,8,7,5,8,7,8
3,Idaline Gadeaux,Edward Reinhart,2,3,4,1,4,4,6,5,...,6,5,6,4,8,7,8,8,8,7
4,Gaspard Dunn,Edward Reinhart,1,1,3,4,3,4,1,1,...,8,8,8,8,8,2,8,8,8,7
5,Reg Mcreynold,Edward Reinhart,1,3,2,1,2,3,4,4,...,8,8,8,8,6,8,8,8,8,8
6,Penni Grioli,Edward Reinhart,3,3,2,5,4,4,3,1,...,8,8,8,6,7,8,8,7,8,4
7,Kial Gowdy,Edward Reinhart,3,2,3,3,1,2,1,2,...,8,5,8,8,6,8,6,8,8,8
8,Haskell Mcdonnell,Edward Reinhart,5,1,1,4,4,1,2,4,...,8,8,5,6,8,8,8,8,8,8
9,Jeffy Dudding,Edward Reinhart,2,3,4,2,2,3,5,2,...,8,8,8,8,6,8,8,6,6,7
10,Damaris Vallance,Edward Reinhart,4,5,3,2,3,2,3,2,...,7,8,8,8,8,7,8,8,8,8
11,Stacee Kidson,Edward Reinhart,2,3,2,3,1,3,5,5,...,8,8,8,8,8,7,8,8,6,8
12,Anica Vallis,Edward Reinhart,1,5,4,2,7,4,5,4,...,8,6,8,6,8,4,8,8,8,8

Data_31_2019-05-20.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Emmey Wadforth,Lucy Foster,4,1,7,3,2,1,1.0,1.0,...,8.0,8.0,8.0,8.0,8.0,7.0,8.0,8.0,8.0,8.0
1,Sayer Weedon,Lucy Foster,1,5,7,1,3,2,6.0,1.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
2,Norbie Iacobucci,Lucy Foster,2,2,1,2,3,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lynnell Samber,Lucy Foster,4,5,1,4,5,2,1.0,3.0,...,6.0,8.0,8.0,8.0,6.0,8.0,8.0,6.0,8.0,8.0
4,Hogan Bushnell,Lucy Foster,1,3,3,2,5,4,4.0,2.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,8.0
5,Scott Duny,Lucy Foster,1,7,5,1,1,3,3.0,2.0,...,8.0,2.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
6,Viv Newby,Lucy Foster,3,3,1,3,2,5,5.0,1.0,...,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0
7,Louise Dowse,Lucy Foster,3,1,7,1,1,4,3.0,5.0,...,5.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
8,Haroun Mccrohon,Lucy Foster,2,5,3,6,5,4,3.0,2.0,...,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
9,Devan Claricoats,Lucy Foster,3,2,2,4,4,4,2.0,2.0,...,8.0,8.0,8.0,5.0,8.0,8.0,8.0,8.0,7.0,8.0
10,Matthaeus Audas,Lucy Foster,5,4,3,3,3,2,1.0,1.0,...,8.0,5.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0
11,Halsey Broader,Lucy Foster,2,1,1,6,3,2,6.0,6.0,...,6.0,8.0,8.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0
12,Rina Soffe,Lucy Foster,4,3,4,4,2,5,4.0,3.0,...,8.0,4.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,7.0

Data_32_2019-07-22.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Marcy Treat,Gina Cartwright,6,5,2,2,4,5,5,3,...,8,7,8,5,8,8,8,7,8,7
1,Heindrick Mckiddin,Gina Cartwright,5,3,2,3,3,3,1,3,...,8,6,7,8,5,7,5,8,5,4
2,Danella Winkett,Gina Cartwright,6,3,6,1,1,3,3,7,...,8,6,8,6,8,8,8,8,8,6
3,Darrin Perrelle,Gina Cartwright,3,1,2,4,6,2,3,5,...,8,5,6,6,3,8,2,7,8,8
4,Janelle Forbear,Gina Cartwright,1,4,1,3,4,6,2,1,...,8,7,8,6,8,8,8,7,8,8
5,Sorcha Argue,Gina Cartwright,1,4,2,4,5,6,2,1,...,6,8,8,8,6,8,8,8,8,8
6,Toddie Rubanenko,Gina Cartwright,6,1,3,4,3,1,1,1,...,8,8,8,6,8,8,6,7,8,7
7,Selby Floyd,Gina Cartwright,4,4,1,4,5,3,2,5,...,8,8,8,4,6,8,8,8,8,6
8,Claudio Handrick,Gina Cartwright,4,3,3,1,4,2,1,3,...,8,4,8,7,8,6,4,4,8,8
9,Kingston Comsty,Gina Cartwright,2,3,5,4,5,3,2,8,...,8,8,8,7,8,8,5,8,8,5
10,Benedikt Cohani,Gina Cartwright,2,1,2,4,1,8,6,1,...,7,8,5,8,8,8,8,8,8,8
11,Morgen Lilywhite,Gina Cartwright,3,2,4,4,4,4,2,5,...,8,8,7,8,7,8,8,8,6,8
12,Job Restall,Gina Cartwright,3,3,2,2,2,4,2,3,...,8,6,8,4,8,8,8,7,8,8
13,Wilhelm Jouanet,Gina Cartwright,1,2,4,3,3,2,5,2,...,8,7,6,6,8,8,8,8,8,7

Data_33_2019-08-05.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Malvina Whiteford,Lucy Foster,3,2,2,6,3,1,2.0,4.0,...,8.0,6.0,8.0,8.0,8.0,8.0,8.0,6.0,8.0,8.0
1,Belle Catherall,Lucy Foster,3,5,4,4,1,1,3.0,8.0,...,8.0,8.0,4.0,7.0,8.0,7.0,8.0,8.0,8.0,8.0
2,Ortensia Winscomb,Lucy Foster,2,2,7,1,2,2,1.0,5.0,...,8.0,8.0,1.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
3,Staffard Load,Lucy Foster,3,4,3,2,4,2,1.0,8.0,...,8.0,8.0,4.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0
4,Bowie Endersby,Lucy Foster,4,5,1,2,2,3,3.0,6.0,...,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0
5,Tonye Ambrogio,Lucy Foster,3,5,3,4,1,2,2.0,1.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
6,Celina Polley,Lucy Foster,2,3,3,6,2,2,2.0,2.0,...,4.0,5.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0
7,Muhammad Linn,Lucy Foster,3,3,2,3,7,1,3.0,2.0,...,8.0,1.0,8.0,4.0,8.0,8.0,8.0,7.0,8.0,8.0
8,Farica Harding,Lucy Foster,4,4,1,3,1,4,5.0,4.0,...,8.0,4.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0
9,Marquita Forrington,Lucy Foster,1,1,4,1,4,1,5.0,6.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
10,Muffin Jandel,Lucy Foster,5,4,3,5,3,1,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Nadya Pineaux,Lucy Foster,5,2,1,4,2,4,3.0,4.0,...,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
12,Dewitt Milborn,Lucy Foster,1,2,2,1,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Levy Standage,Lucy Foster,1,3,8,2,2,5,2.0,6.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0,8.0

Data_34_2019-08-19.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Silvain Kuhwald,Lucy Foster,4,4,1,4,5,4,3,5,...,6,8,4,8,8,8,8,8,8,8
1,Aguie Morrad,Lucy Foster,6,2,1,5,6,5,4,1,...,8,8,8,8,8,8,8,6,8,8
2,Bertram Esgate,Lucy Foster,2,4,3,1,4,3,3,2,...,8,4,8,8,8,7,8,8,8,8
3,Marlon Reside,Lucy Foster,5,2,1,3,1,6,8,5,...,4,8,8,8,8,8,8,8,8,8
4,Micheal Di Matteo,Lucy Foster,2,3,3,1,3,5,2,4,...,8,8,6,8,8,8,6,8,8,8
5,Regina Calver,Lucy Foster,3,4,2,7,6,1,2,3,...,8,7,8,8,8,8,8,8,8,8
6,Jodie Kaygill,Lucy Foster,3,2,1,2,4,1,2,3,...,8,8,8,8,8,8,8,8,8,6
7,Ingunna Adin,Lucy Foster,3,1,4,4,1,3,1,3,...,8,8,6,8,8,8,8,8,8,8
8,Carlos Gerckens,Lucy Foster,1,3,4,4,3,2,1,2,...,7,8,8,8,8,8,8,8,8,8
9,Sherline Cudihy,Lucy Foster,3,4,4,8,1,4,3,6,...,8,8,5,8,8,8,8,8,8,8
10,Trudie Kiellor,Lucy Foster,5,3,5,7,2,4,3,1,...,8,8,7,8,8,8,8,8,8,8

Data_35_2019-09-23.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Edvard Northen,Lucy Foster,3,5,4,3,2,7,5,3,...,6.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
1,Alwin Bullman,Lucy Foster,2,2,4,2,3,3,5,2,...,8.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
2,Bob Rogerson,Lucy Foster,2,4,1,3,3,5,2,3,...,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
3,Kerr Coucha,Lucy Foster,3,5,3,2,3,5,2,5,...,5.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
4,Nancie Mehaffey,Lucy Foster,4,4,5,3,2,1,1,5,...,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
5,Violet Luscombe,Lucy Foster,4,7,2,1,4,2,4,5,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
6,Cora Klausewitz,Lucy Foster,3,1,2,2,3,2,1,2,...,8.0,7.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0
7,Scarface Gallihaulk,Lucy Foster,8,2,2,1,2,1,3,2,...,8.0,8.0,4.0,8.0,8.0,8.0,7.0,8.0,8.0,8.0
8,Anna Lamperti,Lucy Foster,5,3,2,2,5,4,3,2,...,8.0,8.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,7.0
9,Collin Commins,Lucy Foster,2,4,4,4,5,1,2,2,...,4.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,5.0,8.0
10,Chrissy Bartholin,Lucy Foster,2,4,1,3,4,3,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Baird Reynoollds,Lucy Foster,4,3,1,1,1,5,2,3,...,8.0,7.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0
12,Vasili Cartledge,Lucy Foster,3,2,3,2,2,5,4,4,...,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0

Data_36_2019-10-28.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Otes Kemster,Gina Cartwright,1,3,2,4,6,2,1.0,1.0,...,8.0,8.0,8.0,7.0,6.0,8.0,8.0,8.0,8.0,8.0
1,Kahaleel Tatem,Gina Cartwright,5,3,4,3,4,3,3.0,2.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
2,Antonetta Rustedge,Gina Cartwright,3,3,5,4,2,4,1.0,3.0,...,8.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
3,Anestassia Gadman,Gina Cartwright,7,2,2,1,1,4,5.0,3.0,...,7.0,8.0,7.0,5.0,8.0,5.0,8.0,8.0,8.0,8.0
4,Babara Veazey,Gina Cartwright,6,4,3,4,4,3,2.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Candie Senner,Gina Cartwright,2,3,3,2,4,2,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Sydelle Russo,Gina Cartwright,1,4,5,5,1,6,4.0,2.0,...,8.0,8.0,4.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0
7,Warner Harse,Gina Cartwright,3,4,3,1,6,6,1.0,1.0,...,8.0,7.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
8,Tabbatha Kullmann,Gina Cartwright,1,7,4,5,2,4,4.0,6.0,...,7.0,4.0,8.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0
9,Drucie Bianco,Gina Cartwright,6,4,3,3,1,4,4.0,3.0,...,5.0,8.0,7.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0
10,Malvin Penrith,Gina Cartwright,1,4,1,2,2,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Clay Perillo,Gina Cartwright,1,3,6,1,4,3,5.0,8.0,...,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,6.0

Data_37_2019-11-18.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Sandy Droogan,Edward Reinhart,3,2,3,4,6,1,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Othilia Hutton,Edward Reinhart,1,4,1,4,4,2,1,3,...,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
2,Lindon Mee,Edward Reinhart,1,1,1,5,4,2,2,5,...,4.0,8.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0
3,Danella Leisk,Edward Reinhart,3,4,2,4,3,2,5,5,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,6.0
4,Waylan Gors,Edward Reinhart,5,4,1,7,2,1,1,3,...,8.0,8.0,6.0,8.0,8.0,8.0,8.0,7.0,8.0,7.0
5,Gisela Andrea,Edward Reinhart,2,3,3,3,1,5,2,5,...,6.0,8.0,7.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0
6,Augusta Gilfoy,Edward Reinhart,4,6,3,3,2,1,2,3,...,8.0,8.0,4.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0
7,Pier Spatig,Edward Reinhart,1,5,4,3,1,1,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Brenna Mcgroarty,Edward Reinhart,2,6,2,1,1,1,3,2,...,8.0,8.0,7.0,6.0,6.0,8.0,8.0,8.0,8.0,8.0

Data_38_2019-12-16.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Susannah Bengough,John Sandbox,2,4,5,3,6,1,1.0,1.0,...,8.0,8.0,8.0,5.0,6.0,8.0,8.0,8.0,8.0,8.0
1,Madison Getch,John Sandbox,4,4,1,1,2,4,1.0,5.0,...,8.0,8.0,8.0,8.0,7.0,8.0,7.0,8.0,5.0,8.0
2,Leicester Banker,John Sandbox,3,6,4,2,4,5,3.0,7.0,...,4.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,7.0,3.0
3,Murvyn Aers,John Sandbox,4,4,4,3,5,2,1.0,1.0,...,8.0,6.0,7.0,8.0,8.0,6.0,6.0,5.0,8.0,8.0
4,Morley Battell,John Sandbox,5,1,3,2,4,3,5.0,1.0,...,8.0,8.0,8.0,8.0,7.0,8.0,6.0,3.0,8.0,6.0
5,Juliane Jacobssen,John Sandbox,5,6,1,5,2,4,5.0,3.0,...,4.0,4.0,8.0,8.0,6.0,8.0,8.0,6.0,8.0,2.0
6,Teirtza Docharty,John Sandbox,3,1,1,1,2,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Arny Dobrowolny,John Sandbox,6,1,1,3,1,2,2.0,3.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
8,Derby Mcglashan,John Sandbox,5,1,3,4,1,2,2.0,7.0,...,6.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0
9,Sharron Starling,John Sandbox,3,5,4,1,2,1,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Amalea Harrell,John Sandbox,2,3,1,6,5,1,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Finn Maasze,John Sandbox,5,3,5,3,2,2,1.0,1.0,...,7.0,8.0,4.0,8.0,8.0,7.0,3.0,8.0,8.0,7.0

Data_39_2019-12-30.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Gianina Wandless,Trixie Orange,3,1,8,4,4,1,4,1,...,8,8,8,8,8,8,6,8,7,8
1,Kaitlyn Chagg,Trixie Orange,1,4,2,1,3,3,2,4,...,8,8,8,7,8,8,6,5,8,8
2,Scotti Bromfield,Trixie Orange,1,1,2,6,2,6,3,7,...,8,7,8,6,8,7,8,8,4,8
3,Genovera Mattek,Trixie Orange,3,3,3,1,5,2,2,7,...,8,8,8,8,6,6,4,6,8,8
4,Yorgos O'Rourke,Trixie Orange,1,6,3,5,2,5,1,3,...,8,8,8,8,6,8,8,8,8,8

137

In [ ]:
shape(137,62)

In [4]:
s3 = boto3.client('s3')
bucket_name = 'data-eng-223-final-project'
business_ls = []

try:
    response = s3.list_objects_v2(Bucket=bucket_name)
    
    # Check if any objects exist in the bucket
    if 'Contents' in response:
        objects = response['Contents']
        
        # Iterate over the objects and print their keys
        for obj in objects:
            object_key = obj['Key']
            if object_key.startswith('Academy/Business'):
                # print(object_key)
                business_ls.append(object_key)
    else:
        print('No objects found in the bucket.')
        
except Exception as e:
    print(f"Error listing objects: {e}")

rows = 0
for obj_name in business_ls:
    file_name = obj_name.split('/')[-1]  # Extract the file name from the object key
    print(file_name)
    try:
        response = s3.get_object(Bucket=bucket_name, Key=obj_name)
        df = pd.read_csv(response['Body'])
        print(df.columns)
        display(df)
        
        rows+=df.shape[0]
        # Use the DataFrame 'df' for further processing or analysis
    except Exception as e:
        print(f"Error reading file {file_name}: {e}")
print(rows)

Business_20_2019-02-11.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Quintus Penella,Gregor Gomez,1,2,2,1,2,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Simon Murrey,Gregor Gomez,6,1,1,2,4,2,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Gustaf Lude,Gregor Gomez,6,4,1,1,2,3,1.0,1.0,...,8.0,8.0,8.0,6.0,8.0,7.0,8.0,8.0,7.0,8.0
3,Yolanda Fosse,Gregor Gomez,2,1,2,3,3,3,4.0,2.0,...,8.0,7.0,8.0,8.0,8.0,8.0,7.0,8.0,7.0,5.0
4,Lynnett Swin,Gregor Gomez,2,2,4,5,1,2,3.0,2.0,...,7.0,8.0,8.0,8.0,8.0,7.0,8.0,8.0,8.0,8.0
5,Bart Godilington,Gregor Gomez,3,6,1,5,4,1,2.0,1.0,...,6.0,8.0,8.0,7.0,7.0,7.0,8.0,6.0,7.0,8.0
6,Deni Roust,Gregor Gomez,6,3,1,4,4,2,7.0,2.0,...,8.0,8.0,7.0,7.0,7.0,8.0,8.0,8.0,8.0,8.0
7,Gerhard Mcgrath,Gregor Gomez,2,3,3,4,1,1,3.0,6.0,...,8.0,4.0,8.0,8.0,8.0,8.0,7.0,8.0,7.0,8.0

Business_21_2019-03-18.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Benedick Arnhold,Bruce Lugo,5,4,1,2,3,3,7,6,...,8.0,8.0,3.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0
1,Herminia Brettel,Bruce Lugo,5,3,2,3,3,1,4,2,...,8.0,8.0,6.0,8.0,4.0,7.0,8.0,8.0,8.0,8.0
2,Nicolai Nussey,Bruce Lugo,4,1,5,2,2,3,2,4,...,8.0,8.0,8.0,8.0,8.0,6.0,8.0,5.0,5.0,5.0
3,Elora Ellen,Bruce Lugo,3,2,3,4,3,3,2,4,...,7.0,8.0,8.0,8.0,8.0,8.0,4.0,7.0,8.0,7.0
4,Llywellyn Hoggins,Bruce Lugo,1,3,2,2,3,3,4,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Bobbye Hains,Bruce Lugo,3,4,4,1,1,5,3,2,...,8.0,8.0,7.0,7.0,8.0,8.0,7.0,4.0,6.0,8.0
6,Audrye Tobias,Bruce Lugo,5,4,3,5,5,4,4,4,...,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0
7,Georg Battman,Bruce Lugo,1,1,1,6,5,5,7,2,...,8.0,8.0,8.0,8.0,8.0,7.0,8.0,8.0,8.0,6.0
8,Adolph Andreia,Bruce Lugo,3,3,7,1,6,4,3,4,...,2.0,6.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0
9,Ilaire Ord,Bruce Lugo,7,2,6,5,5,1,2,6,...,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0,5.0
10,Thorpe Pettett,Bruce Lugo,6,1,4,4,2,1,7,1,...,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,5.0,8.0
11,Tiphany Gribben,Bruce Lugo,2,1,3,1,2,5,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Pam Hupka,Bruce Lugo,1,5,2,1,5,1,2,3,...,4.0,8.0,8.0,7.0,6.0,6.0,8.0,8.0,7.0,8.0

Business_22_2019-04-15.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Verne Francescuzzi,Gregor Gomez,2,4,1,2,3,4,2,2,...,8,8,8,8,8,8,8,6,7,6
1,Audi Westmacott,Gregor Gomez,2,4,1,3,3,3,5,5,...,8,8,8,8,8,8,8,6,6,8
2,Gae Crutch,Gregor Gomez,6,3,2,3,3,2,2,4,...,8,8,6,8,8,8,8,8,6,8
3,Fowler Crewdson,Gregor Gomez,1,1,3,7,5,5,1,6,...,8,8,8,4,8,8,8,8,8,8
4,Joletta Matzaitis,Gregor Gomez,4,4,3,4,5,6,2,6,...,5,8,8,7,8,8,6,8,7,7
5,Ofelia Helm,Gregor Gomez,1,7,3,1,4,3,5,1,...,8,8,8,8,7,8,8,5,7,6
6,Quinton Kuhnt,Gregor Gomez,2,3,5,4,3,5,4,2,...,8,8,8,8,8,8,8,8,8,8
7,Frankie Mabee,Gregor Gomez,1,3,3,7,2,2,1,2,...,7,8,7,7,8,8,8,3,8,8
8,Cami Burberow,Gregor Gomez,1,5,4,6,3,5,5,1,...,6,8,5,8,4,6,5,4,8,8
9,Gayla Bownas,Gregor Gomez,3,3,4,4,3,3,1,2,...,4,5,4,8,8,8,8,5,8,8
10,Latisha Ibel,Gregor Gomez,2,3,5,4,6,3,4,7,...,8,8,7,7,8,8,8,5,8,8

Business_23_2019-05-20.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Darb Noor,Neil Mccarthy,3,6,2,4,3,2,1,1,...,8.0,8.0,6.0,8.0,8.0,6.0,8.0,8.0,8.0,7.0
1,Adah Spencers,Neil Mccarthy,5,3,2,5,4,3,4,5,...,7.0,8.0,8.0,8.0,8.0,8.0,6.0,8.0,7.0,8.0
2,Kariotta Barense,Neil Mccarthy,4,4,5,2,3,1,2,2,...,8.0,7.0,8.0,8.0,8.0,7.0,8.0,3.0,5.0,8.0
3,Biddy Rapps,Neil Mccarthy,4,4,2,5,5,5,4,3,...,8.0,8.0,8.0,7.0,5.0,5.0,8.0,5.0,8.0,8.0
4,Thatcher Frankish,Neil Mccarthy,3,3,1,3,1,6,3,1,...,7.0,8.0,8.0,8.0,8.0,8.0,6.0,6.0,7.0,8.0
5,Idelle Kidstoun,Neil Mccarthy,4,2,3,3,1,4,1,6,...,8.0,8.0,6.0,5.0,8.0,7.0,5.0,5.0,6.0,7.0
6,Bailey Antrim,Neil Mccarthy,2,4,4,4,5,6,4,2,...,7.0,8.0,7.0,5.0,5.0,6.0,6.0,3.0,8.0,6.0
7,William Dryden,Neil Mccarthy,2,4,2,2,4,4,1,2,...,8.0,8.0,6.0,8.0,8.0,5.0,8.0,7.0,8.0,7.0
8,Dean Burnup,Neil Mccarthy,1,4,2,3,2,2,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Burtie Garfitt,Neil Mccarthy,1,1,5,5,5,3,3,3,...,7.0,8.0,8.0,8.0,7.0,8.0,7.0,8.0,5.0,8.0
10,Maggy Clapison,Neil Mccarthy,2,4,1,2,2,4,2,4,...,5.0,8.0,8.0,6.0,4.0,8.0,8.0,4.0,4.0,8.0
11,Julia Llorens,Neil Mccarthy,5,7,3,2,2,3,2,1,...,3.0,8.0,8.0,8.0,8.0,8.0,8.0,6.0,8.0,8.0

Business_24_2019-07-15.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Sanford Larking,Rachel Richard,3,2,3,4,2,1,2.0,2.0,...,8.0,8.0,8.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0
1,Ulrika Lemerie,Rachel Richard,6,1,3,1,2,2,2.0,3.0,...,4.0,8.0,8.0,8.0,8.0,8.0,8.0,6.0,6.0,4.0
2,Alidia Govett,Rachel Richard,3,5,7,3,3,3,3.0,4.0,...,4.0,8.0,8.0,8.0,8.0,8.0,4.0,8.0,8.0,8.0
3,Angel Matteau,Rachel Richard,4,3,1,2,4,4,4.0,7.0,...,3.0,7.0,8.0,5.0,5.0,8.0,8.0,8.0,6.0,8.0
4,Wolfie Showers,Rachel Richard,1,7,1,4,2,4,3.0,5.0,...,8.0,8.0,8.0,8.0,8.0,8.0,3.0,6.0,6.0,8.0
5,Nicolea Gibbins,Rachel Richard,1,2,3,2,4,3,4.0,5.0,...,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
6,Florina Sudlow,Rachel Richard,7,4,3,3,1,4,4.0,2.0,...,8.0,8.0,5.0,8.0,7.0,8.0,8.0,8.0,7.0,7.0
7,Dianna Brewett,Rachel Richard,8,1,2,5,2,2,4.0,6.0,...,8.0,8.0,8.0,6.0,8.0,8.0,7.0,7.0,8.0,5.0
8,Megan Hallihan,Rachel Richard,1,1,1,2,5,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Sherlocke Baselio,Rachel Richard,2,5,3,4,5,2,3.0,7.0,...,8.0,7.0,8.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0
10,Keen Tripony,Rachel Richard,5,1,3,1,3,6,3.0,2.0,...,8.0,8.0,8.0,8.0,8.0,3.0,8.0,8.0,8.0,8.0
11,Collete Causbey,Rachel Richard,1,7,3,2,3,3,4.0,1.0,...,8.0,3.0,8.0,7.0,5.0,8.0,8.0,8.0,8.0,6.0

Business_25_2019-07-29.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Gabi Ivins,Gregor Gomez,4,1,6,2,1,1,3,2,...,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
1,Melodee Crippen,Gregor Gomez,4,2,5,1,1,3,3,3,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0,8.0,8.0
2,Wilt Gotliffe,Gregor Gomez,1,5,4,2,1,3,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mela Burgill,Gregor Gomez,1,7,2,2,3,5,5,1,...,3.0,8.0,8.0,7.0,8.0,8.0,2.0,6.0,8.0,8.0
4,Uriel Eidelman,Gregor Gomez,8,2,3,6,4,4,2,1,...,8.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
5,Vivienne Blakelock,Gregor Gomez,2,7,1,6,5,4,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Auberon Werny,Gregor Gomez,5,5,6,5,4,2,4,5,...,8.0,8.0,8.0,6.0,8.0,8.0,8.0,8.0,8.0,8.0
7,Nikolaus Gullefant,Gregor Gomez,1,5,4,4,3,6,4,4,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
8,Prentice Van Der Hoeven,Gregor Gomez,3,2,4,3,1,4,3,3,...,8.0,8.0,8.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0
9,Alikee Sawood,Gregor Gomez,2,4,4,1,3,7,1,3,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
10,Guido Lassells,Gregor Gomez,4,3,6,2,3,1,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Verena Townes,Gregor Gomez,4,3,6,2,4,4,4,6,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
12,Kylie Cordell,Gregor Gomez,3,2,7,5,4,4,6,6,...,8.0,8.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0

Business_26_2019-08-12.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Cornelia Artist,Hamzah Melia,3,5,2,4,1,3,2,1,...,8.0,8.0,7.0,8.0,8.0,8.0,8.0,8.0,6.0,8.0
1,Hanni Katt,Hamzah Melia,6,1,2,1,5,7,5,2,...,7.0,8.0,8.0,8.0,6.0,7.0,8.0,8.0,8.0,7.0
2,Eric Spritt,Hamzah Melia,1,4,6,5,1,1,1,6,...,2.0,7.0,7.0,8.0,8.0,8.0,1.0,2.0,6.0,7.0
3,Merrill Mckie,Hamzah Melia,7,3,2,4,2,2,2,3,...,8.0,2.0,8.0,5.0,8.0,8.0,4.0,8.0,8.0,8.0
4,Marcela Riding,Hamzah Melia,3,4,3,2,4,3,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Lea Normington,Hamzah Melia,2,1,3,4,3,1,4,2,...,8.0,7.0,8.0,6.0,8.0,7.0,6.0,8.0,4.0,8.0
6,Aguste Tann,Hamzah Melia,4,3,4,4,3,2,4,2,...,7.0,6.0,6.0,8.0,8.0,8.0,5.0,8.0,8.0,3.0
7,Anet Satterley,Hamzah Melia,7,1,4,2,2,3,1,5,...,8.0,8.0,6.0,8.0,8.0,7.0,8.0,7.0,5.0,7.0
8,Agace O'Shields,Hamzah Melia,4,2,2,3,1,6,1,4,...,3.0,7.0,4.0,2.0,8.0,8.0,8.0,8.0,6.0,8.0

Business_27_2019-09-16.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Matteo Yeowell,Burhan Milner,3,5,2,1,3,5,4,1,...,8,8,8,8,6,8,6,8,8,8
1,Deck Itzchaki,Burhan Milner,2,3,4,2,4,3,2,1,...,8,8,8,8,5,8,8,8,8,8
2,Tarrah Bunny,Burhan Milner,3,6,3,4,3,5,1,1,...,8,8,7,7,8,8,8,8,8,4
3,Fairlie Cogzell,Burhan Milner,5,2,2,3,3,3,3,4,...,8,7,5,7,7,7,8,8,8,8
4,Robinet Renwick,Burhan Milner,3,2,2,3,2,2,1,1,...,7,8,7,8,8,8,8,6,8,4
5,Boote Moan,Burhan Milner,5,4,3,6,2,4,8,4,...,5,7,6,8,8,8,6,6,7,8
6,Vaughn Wallington,Burhan Milner,1,1,2,3,1,4,6,2,...,8,8,8,7,8,8,8,6,8,8
7,Jim Dwerryhouse,Burhan Milner,5,3,4,3,4,2,1,1,...,8,8,7,8,8,8,8,8,8,7
8,Harriett Saffin,Burhan Milner,3,4,3,1,3,5,2,3,...,5,6,8,8,8,8,4,8,8,8
9,Omero Shill,Burhan Milner,4,5,2,1,4,1,4,5,...,5,5,6,8,8,5,8,8,7,8

Business_28_2019-10-21.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W7,Professional_W7,Studious_W7,Imaginative_W7,Analytic_W8,Independent_W8,Determined_W8,Professional_W8,Studious_W8,Imaginative_W8
0,Casey Putten,Elly Kelly,3,1,3,4,6,5,1,3,...,6.0,8.0,8.0,8.0,4.0,7.0,8.0,8.0,6.0,8.0
1,Una Caldicot,Elly Kelly,2,3,5,2,3,4,1,2,...,7.0,8.0,5.0,8.0,7.0,5.0,7.0,8.0,7.0,7.0
2,Riva Mangeot,Elly Kelly,4,7,2,2,2,3,3,1,...,8.0,8.0,4.0,8.0,6.0,8.0,8.0,6.0,6.0,7.0
3,Gery Marchment,Elly Kelly,4,3,4,2,1,1,2,4,...,7.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0
4,Brendan Tithecott,Elly Kelly,3,4,4,3,2,1,2,6,...,8.0,8.0,8.0,8.0,8.0,5.0,8.0,4.0,8.0,6.0
5,Dorice Slides,Elly Kelly,5,2,3,3,4,2,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Kalinda Leebetter,Elly Kelly,2,1,2,4,8,1,3,3,...,7.0,5.0,8.0,8.0,8.0,8.0,8.0,8.0,7.0,6.0
7,Fifi Kingsly,Elly Kelly,3,2,5,3,3,1,5,4,...,8.0,7.0,8.0,8.0,8.0,8.0,5.0,7.0,8.0,3.0
8,Zollie Danks,Elly Kelly,1,3,1,3,5,5,2,5,...,8.0,8.0,8.0,6.0,4.0,8.0,8.0,6.0,7.0,8.0
9,Katleen Trunks,Elly Kelly,2,3,5,4,5,3,2,4,...,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
10,Heida Cossom,Elly Kelly,1,3,2,6,1,2,1,3,...,8.0,8.0,7.0,8.0,4.0,8.0,8.0,8.0,7.0,8.0
11,Nicola Lavall,Elly Kelly,1,3,4,2,2,7,7,6,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,4.0,4.0,6.0

Business_29_2019-11-18.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Rossie Caitlin,Bruce Lugo,1,3,2,2,3,3,3,4,...,6,8,8,8,8,8,8,8,8,8
1,Marmaduke Kiefer,Bruce Lugo,4,4,3,4,5,7,4,1,...,6,8,8,8,8,8,8,6,8,8
2,Dina Mcgookin,Bruce Lugo,2,3,2,4,1,5,4,3,...,8,7,8,3,8,8,8,8,8,8
3,Reuven Kneaphsey,Bruce Lugo,3,3,3,5,2,6,5,2,...,8,8,6,8,8,8,8,8,6,7
4,Stephi Duckering,Bruce Lugo,3,2,2,3,2,1,4,4,...,7,8,7,7,6,8,8,8,8,6
5,Homer Sebborn,Bruce Lugo,5,3,5,2,2,1,2,2,...,8,8,8,8,5,8,8,8,8,8
6,Say Kleinhausen,Bruce Lugo,1,1,5,4,1,4,8,3,...,8,8,4,6,8,8,8,8,8,8
7,Tyler Traynor,Bruce Lugo,1,3,1,2,1,4,1,2,...,6,8,8,5,8,8,8,6,6,8
8,Johnath Tufts,Bruce Lugo,3,4,3,2,4,1,4,5,...,8,6,7,8,8,8,5,8,8,8
9,Kristin Bardill,Bruce Lugo,3,4,1,2,5,3,4,1,...,8,6,8,8,8,8,8,8,7,8

Business_30_2019-12-30.csv
Index(['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10'],
      dtype='object')

,name,trainer,Analytic_W1,Independent_W1,Determined_W1,Professional_W1,Studious_W1,Imaginative_W1,Analytic_W2,Independent_W2,...,Determined_W9,Professional_W9,Studious_W9,Imaginative_W9,Analytic_W10,Independent_W10,Determined_W10,Professional_W10,Studious_W10,Imaginative_W10
0,Timmie Knudsen,Ely Kely,2,2,2,5,1,2,1,3,...,8,8,8,8,8,8,8,8,8,8
1,Mona Orviss,Ely Kely,6,4,3,1,3,1,3,5,...,8,8,8,4,8,8,8,8,8,8
2,Everett O'Clery,Ely Kely,2,6,2,4,2,4,3,4,...,6,6,5,6,8,8,8,8,8,8
3,Konstanze Trynor,Ely Kely,2,2,1,1,3,4,8,1,...,6,8,8,8,8,8,8,8,8,8
4,Robinett Mcphate,Ely Kely,1,6,1,5,1,2,2,4,...,8,8,4,7,8,8,8,8,5,5
5,Ronda Aggis,Ely Kely,1,5,2,4,3,6,6,1,...,8,8,8,8,8,8,8,8,8,8
6,Caril Bayly,Ely Kely,3,3,1,2,1,3,1,1,...,6,7,4,8,8,8,8,8,8,8
7,Mari Lotterington,Ely Kely,4,1,2,5,3,2,4,1,...,7,8,5,8,8,8,8,8,8,8
8,Jacquelynn Savin,Ely Kely,1,2,5,5,1,2,3,3,...,8,8,8,8,8,8,8,8,8,8
9,Ives Weddell,Ely Kely,4,2,2,2,1,4,3,3,...,4,6,8,6,8,8,8,8,8,8
10,Gerda Yuille,Ely Kely,3,4,2,2,3,4,5,5,...,8,8,8,6,8,8,8,8,8,8

121

In [ ]:
# shape(121,62)
'''
columns
['name', 'trainer', 'Analytic_W1', 'Independent_W1', 'Determined_W1',
       'Professional_W1', 'Studious_W1', 'Imaginative_W1', 'Analytic_W2',
       'Independent_W2', 'Determined_W2', 'Professional_W2', 'Studious_W2',
       'Imaginative_W2', 'Analytic_W3', 'Independent_W3', 'Determined_W3',
       'Professional_W3', 'Studious_W3', 'Imaginative_W3', 'Analytic_W4',
       'Independent_W4', 'Determined_W4', 'Professional_W4', 'Studious_W4',
       'Imaginative_W4', 'Analytic_W5', 'Independent_W5', 'Determined_W5',
       'Professional_W5', 'Studious_W5', 'Imaginative_W5', 'Analytic_W6',
       'Independent_W6', 'Determined_W6', 'Professional_W6', 'Studious_W6',
       'Imaginative_W6', 'Analytic_W7', 'Independent_W7', 'Determined_W7',
       'Professional_W7', 'Studious_W7', 'Imaginative_W7', 'Analytic_W8',
       'Independent_W8', 'Determined_W8', 'Professional_W8', 'Studious_W8',
       'Imaginative_W8', 'Analytic_W9', 'Independent_W9', 'Determined_W9',
       'Professional_W9', 'Studious_W9', 'Imaginative_W9', 'Analytic_W10',
       'Independent_W10', 'Determined_W10', 'Professional_W10', 'Studious_W10',
       'Imaginative_W10']
       '''